# Site settings
title: In Lombardia
description: >
  InLombardia site description
baseurl: "/inlombardia"
url: "https://www.secretescapes.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, bower_components, bower.json, README.md]
